const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  defaultDownloadFolder: () => ipcRenderer.invoke('default-download-folder'),
  openFolder: (target) => ipcRenderer.invoke('open-folder', target),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  ytSearch: (query, limit) => ipcRenderer.invoke('yt-search', { query, limit }),
  listExtractors: () => ipcRenderer.invoke('list-extractors'),
  siteList: () => ipcRenderer.invoke('site-list'),
  siteSearch: (siteId, query, limit, page, kind) => ipcRenderer.invoke('site-search', { siteId, query, limit, page, kind }),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  checkBinaries: () => ipcRenderer.invoke('check-binaries'),
  fetchInfo: (url) => ipcRenderer.invoke('fetch-info', url),
  startDownload: (payload) => ipcRenderer.invoke('start-download', payload),
  clientExtract: (url) => ipcRenderer.invoke('client-extract', url),
  playlistInfo: (url, limit) => ipcRenderer.invoke('playlist-info', { url, limit }),
  clientDownload: (payload) => ipcRenderer.invoke('client-download', payload),
  pauseDownload: (id) => ipcRenderer.invoke('pause-download', id),
  resumeDownload: (id) => ipcRenderer.invoke('resume-download', id),
  cancelDownload: (id) => ipcRenderer.invoke('cancel-download', id),
  historyLoad: () => ipcRenderer.invoke('history-load'),
  historySave: (list) => ipcRenderer.invoke('history-save', list),
  windowControl: (action) => ipcRenderer.invoke('window-control', action),
  onProgress: (cb) => ipcRenderer.on('download-progress', (_e, d) => cb(d)),
  onLog: (cb) => ipcRenderer.on('download-log', (_e, d) => cb(d)),
  onDone: (cb) => ipcRenderer.on('download-done', (_e, d) => cb(d)),
  onBridgeDownload: (cb) => ipcRenderer.on('bridge-download', (_e, d) => cb(d)),
  // License
  licenseStatus:    () => ipcRenderer.invoke('license-status'),
  licenseSignup:    (email) => ipcRenderer.invoke('license-signup', email),
  licenseActivate:  (key)   => ipcRenderer.invoke('license-activate', key),
  licenseClear:     () => ipcRenderer.invoke('license-clear'),
  licenseHeartbeat: () => ipcRenderer.invoke('license-heartbeat'),
  // Account screen: plan, usage, pricing and the notices we broadcast.
  accountInfo:    () => ipcRenderer.invoke('account-info'),
  accountRefresh: () => ipcRenderer.invoke('account-refresh'),
  noticeDismiss:  (id) => ipcRenderer.invoke('notice-dismiss', id),
  openStore:      (url) => ipcRenderer.invoke('open-store', url),
  onAccountUpdated: (cb) => ipcRenderer.on('account-updated', (_e, d) => cb(d)),
  onLicenseInvalidated: (cb) => ipcRenderer.on('license-invalidated', (_e, d) => cb(d || {})),
  onLicenseRevoked: (cb) => ipcRenderer.on('license-revoked', () => cb()),
  // New Premium Features
  torrentAdd: (args) => ipcRenderer.invoke('torrent-add', args),
  torrentStart: (args) => ipcRenderer.invoke('torrent-start', args),
  torrentGetFiles: (id) => ipcRenderer.invoke('torrent-get-files', id),
  torrentPause: (id) => ipcRenderer.invoke('torrent-pause', id),
  torrentResume: (id) => ipcRenderer.invoke('torrent-resume', id),
  torrentRemove: (args) => ipcRenderer.invoke('torrent-remove', args),
  selectSavePath: () => ipcRenderer.invoke('select-save-path'),
  openTorrentFile: () => ipcRenderer.invoke('open-torrent-file'),
  openExternalFolder: (path) => ipcRenderer.invoke('open-external-folder', path),
  onTorrentProgress: (cb) => ipcRenderer.on('torrent-progress', (e, d) => cb(d)),
  onTorrentFiles: (cb) => ipcRenderer.on('torrent-files-ready', (_e, d) => cb(d)),
  onTorrentDone: (cb) => ipcRenderer.on('torrent-done', (_e, d) => cb(d)),
  onTorrentError: (cb) => ipcRenderer.on('torrent-error', (_e, d) => cb(d)),
  fitgirlFetch: () => ipcRenderer.invoke('fitgirl-fetch'),
  fitgirlSearch: (query) => ipcRenderer.invoke('fitgirl-search', query),
  fitgirlGetMagnet: (url) => ipcRenderer.invoke('fitgirl-get-magnet', url),
  fitgirlGetInfo: (url) => ipcRenderer.invoke('fitgirl-get-info', url),
  searchGlobal: (query) => ipcRenderer.invoke('search-global', query),
  softwareFetch: () => ipcRenderer.invoke('software-fetch'),
  softwareSearch: (query) => ipcRenderer.invoke('software-search', query),
  searchDuckduckgo: (args) => ipcRenderer.invoke('search-duckduckgo', args),
  // YouTube sign-in hand-off (for videos YouTube refuses anonymously)
  ytSignInGet: () => ipcRenderer.invoke('yt-signin-get'),
  ytSignInSet: (on) => ipcRenderer.invoke('yt-signin-set', on),
  netflixCredsSet: (email, pass, cookies, proxy) => ipcRenderer.invoke('netflix-creds-set', email, pass, cookies, proxy),
  netflixCredsGet: () => ipcRenderer.invoke('netflix-creds-get'),
  proxyFindBest: () => ipcRenderer.invoke('proxy-find-best'),
  // Proxy (a second exit IP for the download engine; not a VPN)
  proxyGet:  () => ipcRenderer.invoke('proxy-get'),
  proxySet:  (patch) => ipcRenderer.invoke('proxy-set', patch),
  proxyTest: (url) => ipcRenderer.invoke('proxy-test', url),
  // Auto-update
  taskbarProgress: (f) => ipcRenderer.invoke('taskbar-progress', f),
  speedLimitGet: () => ipcRenderer.invoke('speed-limit-get'),
  speedLimitSet: (bps) => ipcRenderer.invoke('speed-limit-set', bps),
  appVersion:    () => ipcRenderer.invoke('app-version'),
  updateStatus:  () => ipcRenderer.invoke('update-status'),
  updateCheck:   () => ipcRenderer.invoke('update-check'),
  updateInstall: () => ipcRenderer.invoke('update-install'),
  onUpdateAvailable:  (cb) => ipcRenderer.on('update-available', (_e, d) => cb(d)),
  onUpdateProgress:   (cb) => ipcRenderer.on('update-progress', (_e, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_e, d) => cb(d)),
  onUpdateError:      (cb) => ipcRenderer.on('update-error', (_e, d) => cb(d)),
});
