const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  defaultDownloadFolder: () => ipcRenderer.invoke('default-download-folder'),
  openFolder: (target) => ipcRenderer.invoke('open-folder', target),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  ytSearch: (query, limit) => ipcRenderer.invoke('yt-search', { query, limit }),
  listExtractors: () => ipcRenderer.invoke('list-extractors'),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  checkBinaries: () => ipcRenderer.invoke('check-binaries'),
  fetchInfo: (url) => ipcRenderer.invoke('fetch-info', url),
  startDownload: (payload) => ipcRenderer.invoke('start-download', payload),
  clientExtract: (url) => ipcRenderer.invoke('client-extract', url),
  clientDownload: (payload) => ipcRenderer.invoke('client-download', payload),
  pauseDownload: (id) => ipcRenderer.invoke('pause-download', id),
  resumeDownload: (id) => ipcRenderer.invoke('resume-download', id),
  cancelDownload: (id) => ipcRenderer.invoke('cancel-download', id),
  historyLoad: () => ipcRenderer.invoke('history-load'),
  historySave: (list) => ipcRenderer.invoke('history-save', list),
  windowControl: (action) => ipcRenderer.invoke('window-control', action),
  onProgress: (cb) => ipcRenderer.on('download-progress', (_e, d) => cb(d)),
  onLog: (cb) => ipcRenderer.on('download-log', (_e, d) => cb(d)),
  onDone: (cb) => ipcRenderer.on('download-done', (_e, d) => cb(d)),
  onBridgeDownload: (cb) => ipcRenderer.on('bridge-download', (_e, d) => cb(d)),
  // License
  licenseStatus:    () => ipcRenderer.invoke('license-status'),
  licenseSignup:    (email) => ipcRenderer.invoke('license-signup', email),
  licenseActivate:  (key)   => ipcRenderer.invoke('license-activate', key),
  licenseClear:     () => ipcRenderer.invoke('license-clear'),
  licenseHeartbeat: () => ipcRenderer.invoke('license-heartbeat'),
  onLicenseInvalidated: (cb) => ipcRenderer.on('license-invalidated', (_e, d) => cb(d || {})),
  onLicenseRevoked: (cb) => ipcRenderer.on('license-revoked', () => cb()),
});
